# TODO: set up networking without using host network
version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --save 600 10
    network_mode: host
  app:
    container_name: kleocam
    image: kleocam:latest
    build:
      context: .
      dockerfile: Dockerfile-local
    network_mode: host
    volumes:
      - ./data:/data
