# TODO: set up networking without using host network
version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server --save 600 10
    network_mode: host
    # ports:
    #   - 6379:6379
  app:
    container_name: kleocam
    image: kleocam:latest
    build: .
    network_mode: host
    # depends_on:
    #   - redis
    # links:
    #   - "redis:redis"