FROM python:3.9.6-slim as build

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VERSION=1.1.13

RUN python -m venv /venv
RUN /venv/bin/pip install "poetry==$POETRY_VERSION"

# TODO: dont copy entire repo?
# TODO: can we reuse environment if only copying poetry.lock first?
COPY . /app
WORKDIR /app

RUN /venv/bin/poetry export -f requirements.txt | /venv/bin/pip install -r /dev/stdin
RUN /venv/bin/poetry build && /venv/bin/pip install dist/*.whl


FROM python:3.9-slim

# TODO: Mount instead of copy to capture changes in code
COPY --from=build /venv /venv
COPY --from=build /app /app

WORKDIR /app
RUN mkdir /data

ENV OUTPUT_DIR=/data \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1

CMD cd kleocam && /venv/bin/uvicorn main:app